### ISSUE TITLE
Russian

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#11]
Seems to work. (However, we usually use “regular” American quotation marks in place of vernacular ones when transcribing in Romanization

**Comment by scossu** [comment]
I don't understand the issue at hand. Could you expand?

**Comment by scossu** [comment]
Resolved in f1517b7f3c4cd32e3e48b4898aa69394158be4ca .

**Comment by scossu** [comment]
Note that f1517b7f3c4cd32e3e48b4898aa69394158be4ca uses "straight" quotation marks rather than curly ones due to limitations of the integrated software. This makes it only possible to transliterate script to Roman, not the other way around, because it would be very difficult to know whether the quotation mark is an opening one or a closing one.
