### ISSUE TITLE
Korean: closing punctuation converted to alphanunmeric text 

### ISSUE THREAD

**Issue by tventimi** [lcnetdev/scriptshifter#117]
When the input text ends with multiple punctuation marks in a row, some extraneous alphanumeric text may be generated.  
 
Example JSON request:

`{"text":"[編著者 國立中央博物館].",
"lang":"korean_nonames",
"t_dir":"s2r",
"capitalize":
"no_change","options":{}
}`

The output is

`{"output":"[p'y\u014fnj\u014fja kungnipchungangbangmulgwan SB31TQ.","warnings":[]}`

Note that the right bracket is replaced by "SB31TQ"

**Comment by scossu** [comment]
The issue is with FKR050 (convert punctuation symbols) and FKR066 (restore symbols). they have mappings for symbols in any combination with a leading or trailing space, and something gets lost when converting. I'll try to simplify the logic and only map isolated symbols, and deal with extra spacing in a separate step.

**Comment by scossu** [comment]
This required some major reworking of the Korean module, as it used common punctuation symbols that conflicted with other punctuation in the text. Replacing these symbols with less common Unicode characters resulted in a simplified rule set and less pitfalls.
