### ISSUE TITLE
Ukrainian

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#12]
It doesn’t appear that the apostrophe (which functions, I believe, like the hard sign in Russian) is differentiated from the soft sign in ScriptShifter transliteration

**Comment by scossu** [comment]
This was discussed on 02/24/23. The problem seems to lie in the fact that an apostrophe is sometimes used instead of a soft sign in the source, and the former does not get transliterated.

This can either be left as is to highlight the error in the source, or if we want to be more lenient, add transliteration rules to map the apostrophe to the same characters that the soft sign does. This only applies to script that don't have an apostrophe sign.

**Comment by RandyBarry** [comment]
The apostrophe should NOT be used in Latin transliteration to represent the Cyrillic soft sign. Ukrainian also uses the apostrophe, so the two must have different characters in Latin strings. That is why the character "prime" is used for the soft sign, to differentiate it from the apostophe.

**Comment by scossu** [comment]
We're good then. Thanks.
