### ISSUE TITLE
Azerbaijani (Cyrillic)  Kazakh (Cyrillic)  Kyrgyz (Cyrillic)  Tajik (Cyrillic)  Tatar (Cyrillic)  Uzbek (Cyrillic)

### ISSUE THREAD

**Issue by thisismattmiller** [lcnetdev/scriptshifter#14]
I have tested this language over and over again and also managed to get the screenshots of the books to make sure that nothing is missed. I really like the script shifter and was hoping that it would work well for Cyrillic Azeri since Latin Azeri was not part of it. But as I mentioned earlier unfortunately it doesn't work for certain letters. I will try to if I can insert the examples : This is the title of the book (LCCN#00655035 ) in original Azeri Cyrillic ( I have a screenshot of the cover and title page) Азəрбајҹан Совет əдəбијјатынын поетика мəсəлəлəри : ǂb елми əсəрлəрин тематик мəҹмyеси This is how the ScriptShifter romanized it Azərbai̐jan Sovet ədəbиi̐i̐atыnыn poetиka məsələlərи : ǂb elmи əsərlərиn tematиk məjmyesи This is how correctly it should have been romanized based on LC-ALA romanization table Azărbai̐jan Sovet ădăbii̐i̐atynyn poetika măsălălări : ǂb elmi ăsărlărin tematik măjmu̇esi I will highlight which of the letters were correctly romanized and which failed: This how this letter looks like in the table: Vernacular Romanization ә ă While in some other instances this letter was romanized fine in this particular case as you can see it stayed as vernacular during the romanization process. These two letters: ј,ҹ were romanized correctly both in the 1st word of the tile and others based on the table: ј i̐ ҹ j The next incorrectly romanized letter is a basic и which should be represented by i и i The next incorrect letter is ы which should have been romanized as y ы y The last incorrect letter which is contained in the last word "мəҹмyеси" is the letter "ү" which should have been romanized as u̇ ү u̇ I want to repeat that I have tested several titles. This is a second example: Азәрбајҹан XXI әсрин астанасында" Республика елми-практики конфрансынын : материаллары Azărbai̐jan XXI ăsrиn astanasыnda" Respublиka elmи-praktиkи konfransыnыn : materиallarы The set of letters here is more limited but the in accuracies with the romanization are almost the same. What surprised me here was the fact that ә in the first word "Азәрбајҹан" was romanized correctly which was not a case in previous example. BBut the problem with the letters и and ы stayed the same.

**Comment by scossu** [comment]
- ә -> ă: the issue is with the source letter, which in the reporter's text is ə (Latin Small Letter Schwa, U+0259) while Scriptshifter has a configuration entry for ә (Cyrillic Small Letter Schwa, U+04D9)
- `ј`, `ҹ` are not a problem, correct?
- `и` (U+0438), `ы` (U+044B): these are bona fide table errors. Azerbaijani inherits from _cyrillic_base, and these letters are not defined in either table. 
- `y` in `мəҹмyеси`: this is also an issue with the source string, which has is a Latin "y" letter rather than ү (U+04AF), which is correctly mapped in both upper- and lowercase.

**Comment by minazarova** [comment]
Greetings Matt and Stefano,
As I was looking though this post and preparing to the meeting with Rachel today, it suddenly occurred to me why it was decided not to include Azeri Latin in the script shifter.  What was this decision based upon. we are talking about few peculiar letters and some diacritics. I realize that this might not be one of your top priority languages but if it doen't need much work then why not?  Thanks.  Muzhgan.

**Comment by rrroche** [comment]
I just met with Muzhgan about these issues.

- I agree with Muzhgan that adding a handful of Latin letters might be worth our time. Someone using U+0259 in Azerbaijani they are transliterating almost certainly means to use U+04D9. As a test to make sure I am doing the process correctly, I am adding that to the table, in upper and lower case, in only the script_to_roman section because that is the only area the mistaken character is significant. Please let me know what you think.
- @scossu, you are correct, ј and ҹ are not a problem.
- Thank you for adding those letters!
- Since an accidental Latin "y" (U+0079) could be intended to be "у" (U+0443) or "ү" (U+04AF) in Azerbaijani, it is not as simple to assume what letter is meant, so I did not add anything for that.
- This would need to be entered as a different issue if possible, but would it be possible to add a flag when there are untransliterated Latin-block Unicode characters, or highlight them in some way in the output? Apologies if that has already been discussed in an office hours and I forgot.

**Comment by minazarova** [comment]
Dear Stefano,

We just worked on Azeri script with Rachel and did not touch any other scripts mentioned.  Thank you. Muzhgan.

**Comment by rrroche** [comment]
Dear Muzhgan,

That is okay, I think the title was from the list of language experts, I do not think Stefano thinks all of those scripts are now perfect. We will add new tickets/issues to track the specific problems you find in the other languages, or if you find new issues with Azeri script.

Thank you,
Rachel

**Comment by minazarova** [comment]
Thanks, Rachel. Muzhgan.

From: "rrroche" ***@***.******@***.***>>
Subject: [lcnetdev/scriptshifter] Azerbaijani (Cyrillic) Kazakh (Cyrillic) Kyrgyz (Cyrillic) Tajik (Cyrillic) Tatar (Cyrillic) Uzbek (Cyrillic) (Issue #14)
Date: 25 August 2023 09:32
To: "lcnetdev/scriptshifter" ***@***.******@***.***>>
Cc: "Nazarova, Muzhgan" ***@***.******@***.***>>, "Comment" ***@***.******@***.***>>




CAUTION: This email message has been received from an external source. Please use caution when opening attachments, or clicking on links.

Dear Muzhgan,

That is okay, I think the title was from the list of language experts, I do not think Stefano thinks all of those scripts are now perfect. We will add new tickets/issues to track the specific problems you find in the other languages, or if you find new issues with Azeri script.

Thank you,
Rachel
